spring:
#  main:
#    lazy-initialization: true
  application:
    name: Omni-BE-User
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#  jpa:
#    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jwt:
    secret: ${JWT_SECRET_KEY}

cors:
  urls:
    httpsGatewayURL: ${HTTPS_GATEWAY_URL}

springdoc:
  api-docs:
    path: ${USER_SWAGGER_PATH}
  swagger-ui:
    path: ${USER_SWAGGER_PATH}

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics, startup
  endpoint:
    startup:
      enabled: true
    health:
      show-details: never
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
      percentiles-histogram:
        http.server.requests: true

CARD_SERVER_ADDRESS: ${CARD_SERVER_ADDRESS}
SPONSOR_SERVER_ADDRESS: ${SPONSOR_SERVER_ADDRESS}