spring:
  application:
    name: Omni-BE-User
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

cors:
  urls:
    httpsGatewayURL: ${HTTPS_GATEWAY_URL}

springdoc:
  api-docs:
    path: ${USER_SWAGGER_PATH}
  swagger-ui:
    path: ${USER_SWAGGER_PATH}

CARD_SERVER_ADDRESS: ${CARD_SERVER_ADDRESS}
SPONSOR_SERVER_ADDRESS: ${SPONSOR_SERVER_ADDRESS}